DEV-7961: Login Banner
fedspendingtransparency/data-act-broker-web-app pull request #1622
Opened 2021-12-09 21:34 UTC by dpb-bah

**High level description:**

Adding support for a dynamic banner to appear on the login page. 

**Technical details:**

N/A

**Link to JIRA Ticket:**

[DEV-7961](https://federal-spending-transparency.atlassian.net/browse/DEV-7961)

**Mockup**
N/A

The following are ALL required for the PR to be merged:

Author: 
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled Demo including Design/Testing/Front-end OR Provided Instructions for Local Testing above and in JIRA
- [ ] Verified cross-browser compatibility
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)

Reviewer(s):
- [ ] Design review completed
- [ ] Frontend review completed
- [ ] Merged concurrently with [Backend#2217](https://github.com/fedspendingtransparency/data-act-broker-backend/pull/2217)

2021-12-10 20:14 UTC, alburde1 reviewed
Why are we creating a brand new component and reinventing the wheel instead of just using the existing `Banner` component here?

2021-12-13 21:32 UTC, dpb-bah commented
* Updated to reuse Banner component
* Updated Banner component styles to be consistent and supporting of success and error banners.

2021-12-14 13:03 UTC, alburde1 requested changes

2021-12-14 13:03 UTC, alburde1 commented on src/_scss/layouts/login/loginForm/loginForm.scss
> +	}
Tabbing issues

2021-12-14 13:03 UTC, alburde1 commented on src/js/containers/login/LoginContainer.jsx
> +import * as ReviewHelper from '../../helpers/reviewHelper';
Did we need to import reviewHelper here? Based on these changes it doesn't seem like we use it.

2021-12-14 16:24 UTC, alburde1 approved these changes

2021-12-14 16:24 UTC, merged